version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
  servicesmock:
      image: stoplight/prism:3
      ports:
        - "3100:3100"
      command: >
        mock -p 3100 --host 0.0.0.0 https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-fulltext-search/setup/tests/mock_server/full-text-mock.yaml