version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
  servicesmock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./mock_mappings/mappings:/home/wiremock/mappings
  fdk-fulltext-search:
      image: eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:test
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - elasticsearch
        - servicesmock
        - rabbitmq
      environment:
        - HOST_URL=http://localhost
        - HOST_PORT=8000
        - ELASTIC_HOST=elasticsearch
        - ELASTIC_PORT=9200
        - ELASTIC_TCP_PORT=9300
        - RABBIT_HOST=rabbitmq
        - API_URL=http://servicesmock:8080/
        - REASONING_SERVICE_HOST=http://servicesmock:8080
        - ORGANIZATION_CATALOGUE_BASE_URI=http://servicesmock:8080
        - NEW_REFERENCE_DATA_BASE_URI=http://servicesmock:8080
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"