[tool.poetry]
name = "fdk-fulltext-search"
version = "1.0.0"
description = ""
authors = ["NilsOveTen <nils.ove.tendenes@digdir.no>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "1.1.2"
python-dotenv = "0.16.0"
flask-restful = "0.3.8"
elasticsearch = "7.12.0"
elasticsearch-dsl = "7.3.0"
requests = "2.25.1"
gunicorn = "20.1.0"
flask-cors = "3.0.10"
jsonpath-ng = "1.5.2"
pika = "1.2.0"
feedgen = "0.9.0"
simplejson = "3.17.2"
python-json-logger = "2.0.1"
fdk-rdf-parser = "^0.3.6"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"
pytest-cov = "2.11.1"
pytest-mock = "3.5.1"
mock = "4.0.3"
elasticmock = "1.8.0"
pytest-docker = "^0.10.1"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-annotations = "^2.6.1"
flake8-black = "^0.2.1"
flake8-import-order = "^0.18.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.3.1"
mypy = "^0.812"
pep8-naming = "^0.11.1"
safety = "^1.10.3"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["fdk_fulltext_search"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
