[tool.poetry]
name = "fdk-fulltext-search"
version = "1.0.0"
description = ""
authors = ["NilsOveTen <nils.ove.tendenes@digdir.no>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "2.0.2"
python-dotenv = "0.19.2"
flask-restful = "0.3.9"
elasticsearch = "7.15.2"
elasticsearch-dsl = "7.4.0"
requests = "2.26.0"
gunicorn = "20.1.0"
flask-cors = "3.0.10"
jsonpath-ng = "1.5.3"
pika = "1.2.0"
feedgen = "0.9.0"
simplejson = "3.17.6"
python-json-logger = "2.0.2"
fdk-rdf-parser = "1.3.2"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
pytest-cov = "3.0.0"
pytest-mock = "3.6.1"
mock = "4.0.3"
elasticmock = "1.8.1"
pytest-docker = "^0.10.3"
black = "^21.12b0"
flake8 = "^4.0.1"
flake8-annotations = "^2.7.0"
flake8-black = "^0.2.3"
flake8-import-order = "^0.18.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.11.29"
mypy = "^0.910"
pep8-naming = "^0.12.1"
safety = "^1.10.3"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["fdk_fulltext_search"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
