class IndicesKey:
    INFO_MODEL = "informationmodels"
    INFO_MODEL_ID_KEY = "id"
    CONCEPTS = "concepts"
    CONCEPTS_ID_KEY = "id"
    DATA_SETS = "datasets"
    DATA_SETS_ID_KEY = "_id"
    DATA_SETS_SOURCE_KEY = "_source"
    DATA_SERVICES = "dataservices"
    DATA_SERVICES_ID_KEY = "id"
    INDICES_INFO = "info"
    ALL = "all"
    SEARCHABLE_ALIAS = "searchable"
