name: Deploy to demo

on:
  repository_dispatch:
    types: [deploy-demo]

jobs:
  deploy-demo:
    name: Deploy latest production image to demo environment
    runs-on: ubuntu-latest

    steps:
     - name: Apply Helm template
       run: |
         helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
         helm fetch --untar --untardir ./helm fdk/fdk-fulltext-search
         helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:${{ github.event.client_payload.sha }}" \
         -f ./helm/fdk-fulltext-search/values/demo.yaml \
         ./helm/fdk-fulltext-search/ > ./kubectlapply.yaml
         chmod o+w ./kubectlapply.yaml
         cat kubectlapply.yaml

     - name: Auth gcloud CLI for deploy
       uses: google-github-actions/auth@main
       with:
         credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

     - name: Deploy to GCP
       run: |
         gcloud container clusters get-credentials digdir-fdk-dev --region europe-north1-a --project digdir-fdk-dev
         kubectl apply -f ./kubectlapply.yaml --force
         if ! kubectl --namespace=demo rollout status deployment fdk-fulltext-search; then
          kubectl --namespace=demo rollout undo deployment fdk-fulltext-search
          kubectl --namespace=demo rollout status deployment fdk-fulltext-search
          exit 1
         fi         

     - name: Notify slack
       uses: 8398a7/action-slack@v3
       with:
         mention: 'channel'
         if_mention: failure
         status: ${{ job.status }}
         author_name: 'Application: fdk-fulltext-search | Environment: demo'
         fields: commit,author,workflow
       env:
         GITHUB_TOKEN: ${{ github.token }}
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       if: always()
