name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy-production:
    name: Build, test, publish and deploy to production environment on merge to master branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

    - name: Configure docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker eu.gcr.io

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        pip install poetry==1.1.4
        pip install nox==2020.12.31
        pip install nox-poetry==0.8.1

    - name: Set max map count for elasticsearch
      run: sudo sysctl -w vm.max_map_count=262144

    - name: Build image and run tests with nox
      run: nox

    - name: Tag and publish docker image to Google Cloud
      run: |
        docker tag eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:test eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:$GITHUB_SHA
        docker tag eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:test eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:latest
        docker rmi eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:test
        docker -- push eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search -a

    - name: Apply Helm template
      run: |
        helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
        helm fetch --untar --untardir ./helm fdk/fdk-fulltext-search
        helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/fdk-fulltext-search:$GITHUB_SHA" -f ./helm/fdk-fulltext-search/values/prod.yaml ./helm/fdk-fulltext-search/ > ./kubectlapply.yaml
        chmod o+w ./kubectlapply.yaml
        cat kubectlapply.yaml

    - name: Get kubeconfig file from GKE
      uses: machine-learning-apps/gke-kubeconfig@master
      with:
        application_credentials: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
        project_id: digdir-fdk-prod
        location_zone: europe-north1-a
        cluster_name: digdir-fdk-prod

    - name: Deploy to production
      uses: docker://bitnami/kubectl:latest
      env:
        KUBECONFIG: '/github/workspace/.kube/config'
      with:
        args: "apply -f ./kubectlapply.yaml --force"

    - name: Notify slack
      uses: 8398a7/action-slack@v3
      with:
        mention: 'channel'
        if_mention: failure
        status: ${{ job.status }}
        author_name: 'Application: fdk-fulltext-search | Environment: prod'
        fields: commit,author,workflow,message
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

    - name: Trigger deploy to demo
      uses: peter-evans/repository-dispatch@master
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: deploy-demo
        client-payload: '{"sha": "${{ github.sha }}"}'
